// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WealthWatcher.Api.Data;

#nullable disable

namespace WealthWatcher.Api.Migrations
{
    [DbContext(typeof(WealthDbContext))]
    partial class WealthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WealthWatcher.Api.Models.AppPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetJson")
                        .HasColumnType("text");

                    b.Property<string>("FeatureJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FireJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForecastJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneralJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntegrationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MilestoneJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{\"targets\":[]}");

                    b.Property<bool?>("WebhookRelayEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AppPreferences", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AssetGroupAssignmentSet")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AssetGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetGroupId");

                    b.HasIndex("DisplayName");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetGroups", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ValueShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetKinds", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetKindAssignment", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetKindId")
                        .HasColumnType("uuid");

                    b.HasKey("AssetId", "AssetKindId");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("AssetKindId");

                    b.ToTable("AssetKindAssignments", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetKindGroup", b =>
                {
                    b.Property<Guid>("AssetKindId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("AssetKindId", "AssetGroupId");

                    b.HasIndex("AssetGroupId");

                    b.HasIndex("AssetKindId")
                        .IsUnique();

                    b.ToTable("AssetKindGroups", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetValueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Date", "Time");

                    b.ToTable("AssetValueEntries", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("AssetValueEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetValueEntrySource", b =>
                {
                    b.Property<int>("AssetValueEntryId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExternalValueId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceKind")
                        .HasColumnType("integer");

                    b.Property<int?>("SyncRunId")
                        .HasColumnType("integer");

                    b.HasKey("AssetValueEntryId");

                    b.HasIndex("ExternalValueId");

                    b.HasIndex("SyncRunId");

                    b.ToTable("AssetValueEntrySources", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cadence")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BudgetLines", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.BudgetLineAssetMapping", b =>
                {
                    b.Property<Guid>("BudgetLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.HasKey("BudgetLineId", "AssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("BudgetLineId")
                        .IsUnique();

                    b.ToTable("BudgetLineAssetMappings", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.ExternalValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalValues", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.ExternalValueAssetMapping", b =>
                {
                    b.Property<Guid>("ExternalValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExternalValueId");

                    b.HasIndex("AssetId");

                    b.ToTable("ExternalValueAssetMappings", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationConnectionId", "ExternalId")
                        .IsUnique();

                    b.ToTable("IntegrationAccounts", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationAccountAssetMapping", b =>
                {
                    b.Property<Guid>("IntegrationAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IntegrationAccountId", "Role");

                    b.HasIndex("AssetId");

                    b.ToTable("IntegrationAccountAssetMappings", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialsCiphertext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IntegrationProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OnlyPollDuringMarketTimes")
                        .HasColumnType("boolean");

                    b.Property<int>("SyncMode")
                        .HasColumnType("integer");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PollingIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("PollingScheduleDay")
                        .HasColumnType("integer");

                    b.Property<int>("PollingScheduleType")
                        .HasColumnType("integer");

                    b.Property<string>("PollingScheduleValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationProviderId", "DisplayName")
                        .IsUnique();

                    b.ToTable("IntegrationConnections", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("IntegrationProviders", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.PropertyDetail", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.ToTable("PropertyDetails", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionDisplayNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IntegrationConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecordsAdded")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationConnectionId");

                    b.ToTable("SyncRuns", (string)null);
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.CashAssetValueEntry", b =>
                {
                    b.HasBaseType("WealthWatcher.Api.Models.AssetValueEntry");

                    b.HasDiscriminator().HasValue("CashAssetValueEntry");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.InvestmentAssetValueEntry", b =>
                {
                    b.HasBaseType("WealthWatcher.Api.Models.AssetValueEntry");

                    b.Property<decimal?>("InvestedCapital")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("InvestmentAssetValueEntry");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.PropertyAssetValueEntry", b =>
                {
                    b.HasBaseType("WealthWatcher.Api.Models.AssetValueEntry");

                    b.Property<decimal?>("Mortgage")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PropertyAssetValueEntry");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.CashEntry", b =>
                {
                    b.HasBaseType("WealthWatcher.Api.Models.CashAssetValueEntry");

                    b.HasDiscriminator().HasValue("CashEntry");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.InvestmentEntry", b =>
                {
                    b.HasBaseType("WealthWatcher.Api.Models.InvestmentAssetValueEntry");

                    b.HasDiscriminator().HasValue("InvestmentEntry");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.PropertyEntry", b =>
                {
                    b.HasBaseType("WealthWatcher.Api.Models.PropertyAssetValueEntry");

                    b.HasDiscriminator().HasValue("PropertyEntry");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.Asset", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.AssetGroup", "AssetGroup")
                        .WithMany()
                        .HasForeignKey("AssetGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssetGroup");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetKindAssignment", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.Asset", "Asset")
                        .WithMany("AssetKindAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WealthWatcher.Api.Models.AssetKind", "AssetKind")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssetKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssetKind");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetKindGroup", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.AssetGroup", "AssetGroup")
                        .WithMany("KindMappings")
                        .HasForeignKey("AssetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthWatcher.Api.Models.AssetKind", "AssetKind")
                        .WithMany("GroupMappings")
                        .HasForeignKey("AssetKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetGroup");

                    b.Navigation("AssetKind");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetValueEntry", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.Asset", "Asset")
                        .WithMany("ValueEntries")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetValueEntrySource", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.AssetValueEntry", "AssetValueEntry")
                        .WithOne("SourceLink")
                        .HasForeignKey("WealthWatcher.Api.Models.AssetValueEntrySource", "AssetValueEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WealthWatcher.Api.Models.ExternalValue", "ExternalValue")
                        .WithMany("EntrySources")
                        .HasForeignKey("ExternalValueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WealthWatcher.Api.Models.SyncRun", "SyncRun")
                        .WithMany()
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssetValueEntry");

                    b.Navigation("ExternalValue");

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.BudgetLineAssetMapping", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthWatcher.Api.Models.BudgetLine", "BudgetLine")
                        .WithMany("AssetMappings")
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.ExternalValue", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.IntegrationAccount", "IntegrationAccount")
                        .WithMany("ExternalValues")
                        .HasForeignKey("IntegrationAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationAccount");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.ExternalValueAssetMapping", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.Asset", "Asset")
                        .WithMany("ExternalValueMappings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthWatcher.Api.Models.ExternalValue", "ExternalValue")
                        .WithMany("AssetMappings")
                        .HasForeignKey("ExternalValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ExternalValue");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationAccount", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.IntegrationConnection", "IntegrationConnection")
                        .WithMany("Accounts")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationAccountAssetMapping", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.Asset", "Asset")
                        .WithMany("IntegrationAccountMappings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WealthWatcher.Api.Models.IntegrationAccount", "IntegrationAccount")
                        .WithMany("AssetMappings")
                        .HasForeignKey("IntegrationAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("IntegrationAccount");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationConnection", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.IntegrationProvider", "IntegrationProvider")
                        .WithMany("Connections")
                        .HasForeignKey("IntegrationProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntegrationProvider");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.PropertyDetail", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.Asset", "Asset")
                        .WithOne("PropertyDetail")
                        .HasForeignKey("WealthWatcher.Api.Models.PropertyDetail", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.SyncRun", b =>
                {
                    b.HasOne("WealthWatcher.Api.Models.IntegrationConnection", "IntegrationConnection")
                        .WithMany("SyncRuns")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.InvestmentAssetValueEntry", b =>
                {
                    b.OwnsMany("WealthWatcher.Api.Models.PortfolioPosition", "Positions", b1 =>
                        {
                            b1.Property<int>("InvestmentAssetValueEntryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal>("AveragePrice");

                            b1.Property<decimal>("CurrentPrice");

                            b1.Property<decimal>("CurrentValue");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<decimal>("Quantity");

                            b1.Property<string>("Ticker")
                                .IsRequired();

                            b1.HasKey("InvestmentAssetValueEntryId", "__synthesizedOrdinal");

                            b1.ToTable("AssetValueEntries");

                            b1
                                .ToJson("Positions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InvestmentAssetValueEntryId");
                        });

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.Asset", b =>
                {
                    b.Navigation("AssetKindAssignments");

                    b.Navigation("ExternalValueMappings");

                    b.Navigation("IntegrationAccountMappings");

                    b.Navigation("PropertyDetail");

                    b.Navigation("ValueEntries");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetGroup", b =>
                {
                    b.Navigation("KindMappings");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetKind", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("GroupMappings");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.AssetValueEntry", b =>
                {
                    b.Navigation("SourceLink");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.BudgetLine", b =>
                {
                    b.Navigation("AssetMappings");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.ExternalValue", b =>
                {
                    b.Navigation("AssetMappings");

                    b.Navigation("EntrySources");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationAccount", b =>
                {
                    b.Navigation("AssetMappings");

                    b.Navigation("ExternalValues");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationConnection", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("SyncRuns");
                });

            modelBuilder.Entity("WealthWatcher.Api.Models.IntegrationProvider", b =>
                {
                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
